    jQuery(document).ready(function () {
        if (window.location.href.indexOf("listing_") > -1 || window.location.href.indexOf("listingid") > -1 || window.location.href.indexOf("Listing_") > -1) {

            var listingFooter = jQuery('<footer class="w3-auto" id="footer"> <div class="row grid grid-cols-1 md:grid-cols-2 mb-4 max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8"> <div class="col col-span-1"><img alt="Logo" class="w3-image mb-3" initialwidth="588" src="https://mediavault.point2.com/p2a/htmltext/9161/a1b3/c610/c3e6959e6019b8683402/original.png" /> <div class="footer-text1"> <p>Playa Realtors Corp.<br /> 1st Avenue and 20Th street<br /> Colonia Centro- Playa del Carmen<br /> 77710- QR- Mexico<br /> US &amp; CAN: <a href="tel:18558942500">+1.855.894.2500</a> LOCAL: <a href="tel:+529841865453">+52.984.186.5453</a></p> </div> <div class="footer-social">     <h3>Follow Us:</h3>     <a href="https://twitter.com/PlayaRealtors" target="_blank"><i             class="fab fa-twitter socials"></i></a>     <a href="https://www.facebook.com/PlayaRealtorsRealEstate" target="_blank"><i             class="fab fa-facebook-f socials"></i></a>     <a href="https://www.youtube.com/channel/UCDXlvLAMdrz9oD2jGLttGug" target="_blank"><i             class="fab fa-youtube socials"></i></a>     <a href="https://www.instagram.com/playarealtors/?hl=en" target="_blank"><i             class="fab fa-instagram socials"></i></a>     <a href="https://www.linkedin.com/company/playa-realtors-4u/" target="_blank"><i             class="fab fa-linkedin-in socials"></i></a>     <a href="https://www.pinterest.com/playarealtors4u/" target="_blank"><i      class="fa-brands fa-pinterest socials"></i></a>  </div> </div>  <div class="col col-span-1 flex col-logos-footer flex-col md:flex-row justify-end items-center"><img alt="CIPS Real Estate Logo" initialwidth="588" src="https://mediavault.point2.com/p2a/htmltext/df87/f5ce/3a5f/a8977f70f74c73626411/original.png" /> <img alt="AMPI Playa del Carmen" initialwidth="588" src="https://mediavault.point2.com/p2a/htmltext/e80e/5910/e024/be2fe5f96fe2530494f3/original.png" style="width: 77px; height: 85px;" /> <a href="https://mediavault.point2.com/p2a/htmltext/fab9/7623/2ad1/ce1a0b5b0de09594c1cd/original.png"><img alt="IRM Certificate" src="https://mediavault.point2.com/p2a/htmltext/fab9/7623/2ad1/ce1a0b5b0de09594c1cd/original.png" style="width: 150px; height: 114px;" /></a></div> </div>  <div class="copywrite-bar"> <h6 class="w3-text-white w3-center">Copyright 2021 | <a href="https://www.propertiesinplayadelcarmen.com/aviso_de_privacidad/page_2708993.html">Privacy Policy</a></h6> </div> </footer>');

            jQuery('body').append(listingFooter);
        }

        jQuery(".row-fluid").last().addClass("footerBG");
    });
